title: Coffee Coding
description: Website kedai kopi.
url: https://hermanto-cpu.github.io
theme: jekyll-theme-xyz
author:
  name: Hermanto Prastyawan
  email: hermanto9pras@gmail.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
permalink: pretty
